{
 "title": "racing timeline public",
 "time": { "from": "2023-07-12T23:52:23.293Z", "to": "2023-09-13T11:43:12.823Z" },
 "panels": [
  {
   "title": "map",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "parsedQuery": "OSRA.tsMetrics.aggregate([{\"$sort\":{\"time\":1}},{\"$match\":{\"time\":{\"$gte\":$__timeFrom,\"$lte\":$__timeTo}}},{\"$setWindowFields\":{\"sortBy\":{\"time\":1},\"output\":{\"docsInInterval\":{\"$sum\":1,\"window\":{\"unit\":\"millisecond\",\"range\":[{\"$subtract\":[-1,{\"$toLong\":{\"$divide\":[{\"$subtract\":[{\"$toLong\":$__timeTo},{\"$toLong\":$__timeFrom}]},3000]}}]},\"current\"]}}}}},{\"$addFields\":{\"timeAsLong\":{\"$toLong\":\"$time\"}}},{\"$addFields\":{\"timeHash\":{\"$mod\":[\"$timeAsLong\",\"$docsInInterval\"]}}},{\"$match\":{\"timeHash\":{\"$lte\":50}}},{\"$limit\":3000},{\"$project\":{\"_id\":false,\"labels\":false,\"grafanaFilter\":false,\"wallClockUtc\":false}}])",
     "query": "OSRA.tsMetrics.aggregate([\n   {$sort:{time:1}},\n   {$match:{\n         time:{$gte:$__timeFrom, $lte:$__timeTo}}},\n   {$setWindowFields: {\n         sortBy: { time: 1 },\n         output: {\n               docsInInterval:{\n               $sum:1,\n               window: {\n                  unit:\"millisecond\",\n                  range:[\n                     {$subtract:[-1,{$toLong:{$divide:[{$subtract:[{$toLong:$__timeTo},{$toLong:$__timeFrom}]},3000]}}]},\n                     \"current\"\n                  ],\n               }\n               }\n         }\n         \n      }},\n   {$addFields:{\n   timeAsLong:{$toLong:\"$time\"},\n   }},\n      {$addFields:{\n         timeHash:{$mod:[\"$timeAsLong\",\"$docsInInterval\"]}\n      }},\n      {$match:{timeHash:{$lte:50}}},\n   {$limit:3000},\n   {$project:{_id:false,labels:false,grafanaFilter:false,wallClockUtc:false}},\n\n\n])"
    }
   ]
  },
  {
   "title": "Sessions (drag to zoom)",
   "type": "state-timeline",
   "description": "by date, track and laps",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "parsedQuery": "OSRA.tsMetrics.aggregate([{\"$addFields\":{\"nullrow\":{\"$subtract\":[{\"$convert\":{\"input\":\"$labels.laps\",\"to\":\"int\"}},\"$lap\"]},\"lap\":{\"$cond\":{\"if\":{\"$lt\":[{\"$convert\":{\"input\":\"$labels.laps\",\"to\":\"int\"}},\"$lap\"]},\"then\":null,\"else\":\"$lap\"}},\"total_laps\":{\"$cond\":{\"if\":{\"$lt\":[{\"$convert\":{\"input\":\"$labels.laps\",\"to\":\"int\"}},\"$lap\"]},\"then\":null,\"else\":\"$labels.laps\"}},\"timeAsLong\":{\"$toLong\":\"$time\"}}},{\"$group\":{\"_id\":{\"date\":\"$labels.date\",\"time\":\"$labels.time\",\"track\":\"$labels.track\",\"lap\":\"$lap\",\"sess\":\"$sess2\"},\"total_laps\":{\"$max\":\"$total_laps\"},\"lap\":{\"$max\":\"$lap\"},\"time\":{\"$min\":\"$time\"},\"timeAsLong\":{\"$min\":\"$timeAsLong\"},\"timeAsLongEnd\":{\"$max\":\"$timeAsLong\"},\"lap_time\":{\"$max\":\"$sec_in_lap\"},\"sess\":{\"$first\":\"$sess\"}}},{\"$addFields\":{\"timeAsLongDay\":{\"$add\":[\"$timeAsLong\",50000000]}}},{\"$addFields\":{\"url\":{\"$concat\":[\"https://albertingo.grafana.net/public-dashboards/af77d02b79094be7afdf6f50bb40c46a?orgId=1&from=\",{\"$toString\":\"$timeAsLong\"},\"&to=\",{\"$toString\":\"$timeAsLongEnd\"}]}}},{\"$addFields\":{\"url24h\":{\"$concat\":[\"https://albertingo.grafana.net/public-dashboards/af77d02b79094be7afdf6f50bb40c46a?orgId=1&from=\",{\"$toString\":\"$timeAsLong\"},\"&to=\",{\"$toString\":\"$timeAsLongDay\"}]}}}])",
     "query": "OSRA.tsMetrics.aggregate([\n   {$addFields:{\n         nullrow:{$subtract:[{$convert:{  input:\"$labels.laps\",to:\"int\"}},\"$lap\"]},\n      lap:{$cond:{if:{$lt:[{$convert:{  input:\"$labels.laps\",to:\"int\"}},\"$lap\"]}, then:null, else:\"$lap\"}},\n      total_laps:{$cond:{if:{$lt:[{$convert:{  input:\"$labels.laps\",to:\"int\"}},\"$lap\"]}, then:null, else:\"$labels.laps\"}},\n      timeAsLong:{$toLong:\"$time\"},\n   }},\n   {$group:{_id:{date:\"$labels.date\", time:\"$labels.time\", track:\"$labels.track\", lap:\"$lap\", sess:\"$sess2\"},\n            total_laps:{\n               $max:\"$total_laps\",\n               },\n               lap:{$max:\"$lap\"},\n               time:{$min:\"$time\"},\n               timeAsLong:{$min:\"$timeAsLong\"},\n              timeAsLongEnd:{$max:\"$timeAsLong\"},\n            lap_time:{$max:\"$sec_in_lap\"},\n            sess:{$first:\"$sess\"},\n           }\n  } ,\n  {$addFields:{timeAsLongDay:{$add:[\"$timeAsLong\", 50000000]}}},\n  {$addFields:{url:{$concat:[\"https://albertingo.grafana.net/public-dashboards/af77d02b79094be7afdf6f50bb40c46a?orgId=1&from=\",{$toString:\"$timeAsLong\"},\"&to=\",{$toString:\"$timeAsLongEnd\"}]}}},\n  {$addFields:{url24h:{$concat:[\"https://albertingo.grafana.net/public-dashboards/af77d02b79094be7afdf6f50bb40c46a?orgId=1&from=\",{$toString:\"$timeAsLong\"},\"&to=\",{$toString:\"$timeAsLongDay\"}]}}},\n   \n])"
    }
   ]
  },
  {
   "title": "Lap times",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "parsedQuery": "OSRA.tsLaps.aggregate([{\"$match\":{\"time\":{\"$gte\":$__timeFrom,\"$lte\":$__timeTo}}},{\"$limit\":30000},{\"$project\":{\"_id\":false,\"grafanaFilter\":false,\"wallClockUtc\":false}},{\"$group\":{\"_id\":{\"lap\":\"$lap\",\"track\":\"$labels.track\",\"sess\":{\"$concat\":[\"$labels.date\",\" \",\"$labels.track\",\" \",\"$labels.time\"]},\"time\":\"$time\"},\"seconds\":{\"$max\":\"$time_lap\"},\"time\":{\"$min\":\"$time\"}}},{\"$project\":{\"_id.sess\":false,\"_id.time\":false,\"_id.track\":false}},{\"$sort\":{\"time\":1}}])",
     "query": "OSRA.tsLaps.aggregate([\n   {$match:{\n         time:{$gte:$__timeFrom, $lte:$__timeTo}}},\n   {$limit:30000},\n   {$project:{_id:false,grafanaFilter:false,wallClockUtc:false}},\n\n\n   {$group:{_id:{lap:\"$lap\",\n                  track:\"$labels.track\",\n                  sess:{$concat:[\"$labels.date\",\" \",\"$labels.track\",\" \",\"$labels.time\"]},\n                  time:\"$time\"\n                  }, \n            seconds:{$max:\"$time_lap\"},\n            time:{$min:\"$time\"},\n      }},\n   {$project:{\"_id.sess\":false, \"_id.time\":false,\"_id.track\":false}},\n   {$sort:{time:1}}\n\n\n   \n])"
    }
   ]
  },
  {
   "title": "Speed (km/h)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "parsedQuery": "OSRA.tsMetrics.aggregate([{\"$sort\":{\"time\":1}},{\"$match\":{\"time\":{\"$gte\":$__timeFrom,\"$lte\":$__timeTo}}},{\"$setWindowFields\":{\"sortBy\":{\"time\":1},\"output\":{\"docsInInterval\":{\"$sum\":1,\"window\":{\"unit\":\"millisecond\",\"range\":[{\"$subtract\":[-1,{\"$toLong\":{\"$divide\":[{\"$subtract\":[{\"$toLong\":$__timeTo},{\"$toLong\":$__timeFrom}]},10000]}}]},\"current\"]}}}}},{\"$addFields\":{\"timeAsLong\":{\"$toLong\":\"$time\"}}},{\"$addFields\":{\"timeHash\":{\"$mod\":[\"$timeAsLong\",\"$docsInInterval\"]}}},{\"$match\":{\"timeHash\":0}},{\"$limit\":10000},{\"$project\":{\"_id\":false,\"labels\":false,\"grafanaFilter\":false,\"wallClockUtc\":false}}])",
     "query": "OSRA.tsMetrics.aggregate([\n   {$sort:{time:1}},\n   {$match:{\n         time:{$gte:$__timeFrom, $lte:$__timeTo}}},\n   {$setWindowFields: {\n         sortBy: { time: 1 },\n         output: {\n               docsInInterval:{\n               $sum:1,\n               window: {\n                  unit:\"millisecond\",\n                  range:[\n                     {$subtract:[-1,{$toLong:{$divide:[{$subtract:[{$toLong:$__timeTo},{$toLong:$__timeFrom}]},10000]}}]},\n                     \"current\"\n                  ],\n               }\n               }\n         }\n         \n      }},\n   {$addFields:{\n   timeAsLong:{$toLong:\"$time\"},\n   }\n   },\n      {$addFields:{\n         timeHash:{$mod:[\"$timeAsLong\",\"$docsInInterval\"]}\n      }},\n      {$match:{timeHash:0}},\n   {$limit:10000},\n   {$project:{_id:false,labels:false,grafanaFilter:false,wallClockUtc:false}},\n\n\n])"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "parsedQuery": "OSRA.tsMetrics.aggregate([{\"$sort\":{\"time\":1}},{\"$match\":{\"time\":{\"$gte\":$__timeFrom,\"$lte\":$__timeTo}}},{\"$setWindowFields\":{\"sortBy\":{\"time\":1},\"output\":{\"docsInInterval\":{\"$sum\":1,\"window\":{\"unit\":\"millisecond\",\"range\":[{\"$subtract\":[-1,{\"$toLong\":{\"$divide\":[{\"$subtract\":[{\"$toLong\":$__timeTo},{\"$toLong\":$__timeFrom}]},10000]}}]},\"current\"]}}}}},{\"$addFields\":{\"timeAsLong\":{\"$toLong\":\"$time\"}}},{\"$addFields\":{\"timeHash\":{\"$mod\":[\"$timeAsLong\",\"$docsInInterval\"]}}},{\"$match\":{\"timeHash\":0}},{\"$limit\":10000},{\"$project\":{\"_id\":false,\"labels\":false,\"grafanaFilter\":false,\"wallClockUtc\":false}},{\"$project\":{\"time\":1,\"RPM\":1,\"lap\":1}}])",
     "query": "OSRA.tsMetrics.aggregate([\n   {$sort:{time:1}},\n   {$match:{\n         time:{$gte:$__timeFrom, $lte:$__timeTo}}},\n   {$setWindowFields: {\n         sortBy: { time: 1 },\n         output: {\n               docsInInterval:{\n               $sum:1,\n               window: {\n                  unit:\"millisecond\",\n                  range:[\n                     {$subtract:[-1,{$toLong:{$divide:[{$subtract:[{$toLong:$__timeTo},{$toLong:$__timeFrom}]},10000]}}]},\n                     \"current\"\n                  ],\n               }\n               }\n         }\n         \n      }},\n   {$addFields:{\n   timeAsLong:{$toLong:\"$time\"},\n   }\n   },\n      {$addFields:{\n         timeHash:{$mod:[\"$timeAsLong\",\"$docsInInterval\"]}\n      }},\n      {$match:{timeHash:0}},\n   {$limit:10000},\n   {$project:{_id:false,labels:false,grafanaFilter:false,wallClockUtc:false}},\n\n\n\n   {$project:{time:1,RPM:1,lap:1}}\n])"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "parsedQuery": "OSRA.tsMetrics.aggregate([{\"$sort\":{\"time\":1}},{\"$match\":{\"time\":{\"$gte\":$__timeFrom,\"$lte\":$__timeTo}}},{\"$setWindowFields\":{\"sortBy\":{\"time\":1},\"output\":{\"docsInInterval\":{\"$sum\":1,\"window\":{\"unit\":\"millisecond\",\"range\":[{\"$subtract\":[0,{\"$toLong\":{\"$divide\":[{\"$subtract\":[{\"$toLong\":$__timeTo},{\"$toLong\":$__timeFrom}]},10000]}}]},\"current\"]}}}}},{\"$addFields\":{\"timeAsLong\":{\"$toLong\":\"$time\"}}},{\"$addFields\":{\"timeHash\":{\"$mod\":[\"$timeAsLong\",\"$docsInInterval\"]}}},{\"$match\":{\"timeHash\":0}},{\"$limit\":10000},{\"$project\":{\"_id\":false,\"labels\":false,\"grafanaFilter\":false,\"wallClockUtc\":false}},{\"$project\":{\"time\":1,\"T1\":1,\"T2\":2,\"lap\":1}}])",
     "query": "OSRA.tsMetrics.aggregate([\n   {$sort:{time:1}},\n   {$match:{\n         time:{$gte:$__timeFrom, $lte:$__timeTo}}},\n   {$setWindowFields: {\n         sortBy: { time: 1 },\n         output: {\n               docsInInterval:{\n               $sum:1,\n               window: {\n                  unit:\"millisecond\",\n                  range:[\n                     {$subtract:[0,{$toLong:{$divide:[{$subtract:[{$toLong:$__timeTo},{$toLong:$__timeFrom}]},10000]}}]},\n                     \"current\"\n                  ],\n\n               }\n               }\n         }\n         \n      }},\n   {$addFields:{\n   timeAsLong:{$toLong:\"$time\"},\n   }\n   },\n      {$addFields:{\n         timeHash:{$mod:[\"$timeAsLong\",\"$docsInInterval\"]}\n      }},\n      {$match:{timeHash:0}},\n   {$limit:10000},\n   {$project:{_id:false,labels:false,grafanaFilter:false,wallClockUtc:false}},\n\n\n\n   {$project:{time:1,T1:1,T2:2,lap:1}}\n])"
    }
   ]
  },
  {
   "title": "Pick and choose...",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "parsedQuery": "OSRA.tsMetrics.aggregate([{\"$sort\":{\"time\":1}},{\"$match\":{\"time\":{\"$gte\":$__timeFrom,\"$lte\":$__timeTo}}},{\"$setWindowFields\":{\"sortBy\":{\"time\":1},\"output\":{\"docsInInterval\":{\"$sum\":1,\"window\":{\"unit\":\"millisecond\",\"range\":[{\"$subtract\":[-1,{\"$toLong\":{\"$divide\":[{\"$subtract\":[{\"$toLong\":$__timeTo},{\"$toLong\":$__timeFrom}]},2000]}}]},\"current\"]}}}}},{\"$addFields\":{\"timeAsLong\":{\"$toLong\":\"$time\"}}},{\"$addFields\":{\"timeHash\":{\"$mod\":[\"$timeAsLong\",\"$docsInInterval\"]}}},{\"$match\":{\"timeHash\":0}},{\"$limit\":2000},{\"$project\":{\"_id\":false,\"labels\":false,\"grafanaFilter\":false,\"wallClockUtc\":false}}])",
     "query": "OSRA.tsMetrics.aggregate([\n   {$sort:{time:1}},\n   {$match:{\n         time:{$gte:$__timeFrom, $lte:$__timeTo}}},\n   {$setWindowFields: {\n         sortBy: { time: 1 },\n         output: {\n               docsInInterval:{\n               $sum:1,\n               window: {\n                  unit:\"millisecond\",\n                  range:[\n                     {$subtract:[-1,{$toLong:{$divide:[{$subtract:[{$toLong:$__timeTo},{$toLong:$__timeFrom}]},2000]}}]},\n                     \"current\"\n                  ],\n\n               }\n               }\n         }\n         \n      }},\n   {$addFields:{\n   timeAsLong:{$toLong:\"$time\"},\n   }\n   },\n      {$addFields:{\n         timeHash:{$mod:[\"$timeAsLong\",\"$docsInInterval\"]}\n      }},\n      {$match:{timeHash:0}},\n   {$limit:2000},\n   {$project:{_id:false,labels:false,grafanaFilter:false,wallClockUtc:false}},\n\n\n\n])"
    }
   ]
  },
  {
   "title": "Tyre pressure ",
   "type": "barchart",
   "description": "by date, track and laps",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "parsedQuery": "OSRA.tyres.aggregate([{\"$sort\":{\"time\":1}},{\"$match\":{\"time\":{\"$gte\":$__timeFrom,\"$lte\":$__timeTo}}},{\"$setWindowFields\":{\"sortBy\":{\"time\":1},\"output\":{\"docsInInterval\":{\"$sum\":1,\"window\":{\"unit\":\"millisecond\",\"range\":[{\"$subtract\":[-1,{\"$toLong\":{\"$divide\":[{\"$subtract\":[{\"$toLong\":$__timeTo},{\"$toLong\":$__timeFrom}]},10000]}}]},\"current\"]}}}}},{\"$addFields\":{\"timeAsLong\":{\"$toLong\":\"$time\"},\"time2\":{\"$arrayElemAt\":[\"$times\",1]},\"datetime\":{\"$concat\":[\"$cold.labels.date\",\"T\",\"$cold.labels.time\"]}}},{\"$addFields\":{\"timeHash\":{\"$mod\":[\"$timeAsLong\",\"$docsInInterval\"]}}},{\"$match\":{\"timeHash\":0}},{\"$limit\":10000},{\"$project\":{\"datetime\":true,\"source_csv\":true,\"cold\":{\"immatriculation\":true,\"ambient\":{\"T_cold\":{\"$ifNull\":[\"$cold.ambient.T_cold\",-9999]},\"T_hot\":{\"$ifNull\":[\"$cold.ambient.T_hot\",-9999]}},\"front\":{\"left\":{\"P\":true,\"T1\":true,\"T2\":true,\"T3\":true},\"right\":{\"T3\":true,\"T2\":true,\"T1\":true,\"P\":true}},\"rear\":{\"left\":{\"P\":true,\"T1\":true,\"T2\":true,\"T3\":true},\"right\":{\"T3\":true,\"T2\":true,\"T1\":true,\"P\":true}},\"time\":true,\"time2\":true},\"hot\":{\"immatriculation\":{\"$toLong\":\"$immatriculation\"},\"ambient\":{\"T_cold\":{\"$ifNull\":[\"$cold.ambient.T_cold\",-9999]},\"T_hot\":{\"$ifNull\":[\"$cold.ambient.T_hot\",-9999]}},\"front\":{\"left\":{\"P\":true,\"T1\":true,\"T2\":true,\"T3\":true},\"right\":{\"T3\":true,\"T2\":true,\"T1\":true,\"P\":true}},\"rear\":{\"left\":{\"P\":true,\"T1\":true,\"T2\":true,\"T3\":true},\"right\":{\"T3\":true,\"T2\":true,\"T1\":true,\"P\":true}},\"time\":true},\"time\":true,\"time2\":true}},{\"$project\":{\"P\":[{\"rear_left\":{\"$multiply\":[-1,\"$cold.rear.left.P\"]},\"front_left\":\"$cold.front.left.P\",\"front_right\":\"$cold.front.right.P\",\"rear_right\":{\"$multiply\":[-1,\"$cold.rear.right.P\"]},\"hotcold\":\"cold\",\"hcn\":-1,\"time\":\"$time\"},{\"rear_left\":{\"$multiply\":[-1,\"$hot.rear.left.P\"]},\"front_left\":\"$hot.front.left.P\",\"front_right\":\"$hot.front.right.P\",\"rear_right\":{\"$multiply\":[-1,\"$hot.rear.right.P\"]},\"hotcold\":\"hot\",\"hcn\":1,\"time\":\"$time2\"}]}},{\"$unwind\":\"$P\"},{\"$sort\":{\"time\":1}}])",
     "query": "OSRA.tyres.aggregate([\n   {$sort:{time:1}},\n   {$match:{\n         time:{$gte:$__timeFrom, $lte:$__timeTo}}},\n   {$setWindowFields: {\n         sortBy: { time: 1 },\n         output: {\n               docsInInterval:{\n               $sum:1,\n               window: {\n                  unit:\"millisecond\",\n                  range:[\n                     {$subtract:[-1,{$toLong:{$divide:[{$subtract:[{$toLong:$__timeTo},{$toLong:$__timeFrom}]},10000]}}]},\n                     \"current\"\n                  ],\n               }\n               }\n         }\n         \n      }},\n   {$addFields:{\n   timeAsLong:{$toLong:\"$time\"},\n   time2:{$arrayElemAt:[\"$times\",1]},\n   datetime:{$concat:[\"$cold.labels.date\",\"T\",\"$cold.labels.time\"]}\n   }\n   },\n      {$addFields:{\n         timeHash:{$mod:[\"$timeAsLong\",\"$docsInInterval\"]}\n      }},\n      {$match:{timeHash:0}},\n   {$limit:10000},\n\n\n\n\n\n   {$project:{\ndatetime:true,\nsource_csv:true,\ncold:{\n   immatriculation:true,\n   ambient:{\n      T_cold:{$ifNull:[\"$cold.ambient.T_cold\",-9999]},\n      T_hot:{$ifNull:[\"$cold.ambient.T_hot\",-9999]},\n   }, \n   front:{\n      left:{\n         P:true,\n         T1:true,\n         T2:true,\n         T3:true\n   },\n   right:{\n      T3:true,\n      T2:true,\n      T1:true,\n      P:true\n   }\n},\nrear:{\n   left:{\n      P:true,\n      T1:true,\n      T2:true,\n      T3:true\n   },\n   right:{\n      T3:true,\n      T2:true,\n      T1:true,\n      P:true\n   }\n},\ntime:true,\ntime2:true,\n},\n\n\nhot:{\n   immatriculation:{$toLong:\"$immatriculation\"},\n   ambient:{\n      T_cold:{$ifNull:[\"$cold.ambient.T_cold\",-9999]},\n      T_hot:{$ifNull:[\"$cold.ambient.T_hot\",-9999]},\n   },\n   front:{\n      left:{\n         P:true,\n         T1:true,\n         T2:true,\n         T3:true\n   },\n   right:{\n      T3:true,\n      T2:true,\n      T1:true,\n      P:true\n   }\n},\nrear:{\n   left:{\n      P:true,\n      T1:true,\n      T2:true,\n      T3:true\n   },\n   right:{\n      T3:true,\n      T2:true,\n      T1:true,\n      P:true\n   }\n},\ntime:true,\n},\ntime:true,\ntime2:true,\n\n}},\n\n\n\n{$project:{\n   P:[{rear_left:{$multiply:[-1,\"$cold.rear.left.P\"]},\n                  front_left:\"$cold.front.left.P\",\n                  front_right:\"$cold.front.right.P\",\n                  rear_right:{$multiply:[-1,\"$cold.rear.right.P\"]},\n                  hotcold: \"cold\",\n                  hcn:-1,\n                  time:\"$time\",\n                  },\n                  {rear_left:{$multiply:[-1,\"$hot.rear.left.P\"]},\n                  front_left:\"$hot.front.left.P\",\n                  front_right:\"$hot.front.right.P\",\n                  rear_right:{$multiply:[-1,\"$hot.rear.right.P\"]},\n                  hotcold: \"hot\",\n                  hcn: 1,\n                  time:\"$time2\",\n                  }],\n}},\n{$unwind:\"$P\"},\n{$sort:{time:1}},\n\n\n\n])"
    }
   ]
  }
 ]
}